### ISSUE TITLE
Problem converting plugy stash

### ISSUE THREAD

**Issue by LewwOnyw** [pairofdocs/atma-stash-d2r#1]
Hey there!

Thanks for coding this, potentially it can save me a long time manually transferring items :)

I'm trying to convert my old plugy stash (.SSS-file) from D2(LOD) version 1.14 to some kind of stash I can use in GoMule. So I upload the .SSS file and get a .D2I file. Everything seems fine. But when I load this file into GoMule, it just locks up and I have to kill the process.

I've tried re-converting the .D2I file to a .D2X file and load that in to cGoMule, but I get an error:

```
Error

Stash Version Incorrect!
	at gomule.d2x.D2Stash.readAtmaItems(D2Stash.java:153)
	at gomule.d2x.D2Stash.<init>(D2Stash.java:78)
	at gomule.gui.D2FileManager.addItemList(D2FileManager.java:1594)
	at gomule.gui.D2ViewStash.connect(D2ViewStash.java:345)
```

I thought maybe I had to use the "Convert Atma version 96 (LoD) .d2x stash to Atma version 97 (D2R) .d2x stash" for it to work, but when I upload the .D2X file it returns a new .D2X file with only the content "undefined".

Can you guide me or tell me what I'm doing wrong? Much appreciated :)

Sincerely,

Jens Olsen

**Comment by LewwOnyw** [comment]
Nevermind, I manually moved everything insted... took a while, but got it done :)

**Comment by pairofdocs** [comment]
@LewwOnyw hey, sorry I didnt see this issue until now

The problem might have been an item that the converter was failing on. I saw issues with quest items before (like meph's soulstone, or scroll of inifuss)

**Comment by pairofdocs** [comment]
If you still have your old .sss plugy file, can you share that?

**Comment by LewwOnyw** [comment]
Hey there - no worries man :) I've uploaded the file here.
[_LOD_SharedStashSave.zip](https://github.com/pairofdocs/atma-stash-d2r/files/7463961/_LOD_SharedStashSave.zip)
e

**Comment by pairofdocs** [comment]
That's a lot of juvies! 
![image](https://user-images.githubusercontent.com/76428136/140234709-f20f8e45-a933-46cf-b6d2-836faa7d53da.png)

I was able to convert the `.sss` to `.d2i` and load it into gomule from https://github.com/pairofdocs/gomule-d2r

For gomule from Silos https://gomule.sourceforge.io/
that `.d2i` file should be a `.d2x`  and the converter https://pairofdocs.github.io/atma-stash-d2r/ gave me a .d2x

It's kinda confusing.  the `.d2x` that comes out of a `d2i --> d2x` conversion is a D2R d2x file (version 97) and that will only work with the D2R gomule from Silos (it won't work with classic gomule)

**Comment by LewwOnyw** [comment]
Thanks a bunch for following up! :)

Yeah, I stored a bunch of rejuvs hoping to get a pally for Uber Tristam and
just kept saving :P

I'll try out your solution, thanks for contributing to the community!

Sincerely,

Jens

Den tor. 4. nov. 2021 kl. 00.57 skrev pairofdocs ***@***.***>:
